apiVersion: user.rabbitmqtf.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/user
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    passwordSecretRef:
      key: example-key
      name: example-secret
    tags:
    - administrator
    - management
