apiVersion: permissions.rabbitmqtf.m.crossplane.io/v1alpha1
kind: Permissions
metadata:
  annotations:
    meta.upbound.io/example-id: permissions/v1alpha1/permissions
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    permissions:
    - configure: .*
      read: .*
      write: .*
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: user.rabbitmqtf.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: permissions/v1alpha1/permissions
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    passwordSecretRef:
      key: example-key
      name: example-secret
    tags:
    - administrator

---

apiVersion: vhost.rabbitmqtf.m.crossplane.io/v1alpha1
kind: Vhost
metadata:
  annotations:
    meta.upbound.io/example-id: permissions/v1alpha1/permissions
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider: {}
