apiVersion: vhost.rabbitmqtf.crossplane.io/v1alpha1
kind: Vhost
metadata:
  annotations:
    meta.upbound.io/example-id: vhost/v1alpha1/vhost
  labels:
    testing.upbound.io/example-name: my_vhost
  name: my-vhost
spec:
  forProvider:
    defaultQueueType: quorum
    description: My Vhost
    maxConnections: "200"
    maxQueues: 100
    tracing: true
