apiVersion: shovel.rabbitmqtf.m.crossplane.io/v1alpha1
kind: Shovel
metadata:
  annotations:
    meta.upbound.io/example-id: shovel/v1alpha1/shovel
  labels:
    testing.upbound.io/example-name: shovelTest
  name: shoveltest
  namespace: crossplane-system
spec:
  forProvider:
    info:
    - destinationQueue: ${rabbitmq_queue.test.name}
      destinationUri: amqp:///test
      sourceExchange: ${rabbitmq_exchange.test.name}
      sourceExchangeKey: test
      sourceUri: amqp:///test
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: exchange.rabbitmqtf.m.crossplane.io/v1alpha1
kind: Exchange
metadata:
  annotations:
    meta.upbound.io/example-id: shovel/v1alpha1/shovel
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    settings:
    - autoDelete: true
      durable: false
      type: fanout
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: queue.rabbitmqtf.m.crossplane.io/v1alpha1
kind: Queue
metadata:
  annotations:
    meta.upbound.io/example-id: shovel/v1alpha1/shovel
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    settings:
    - autoDelete: true
      durable: false
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: vhost.rabbitmqtf.m.crossplane.io/v1alpha1
kind: Vhost
metadata:
  annotations:
    meta.upbound.io/example-id: shovel/v1alpha1/shovel
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider: {}
