// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/Volevanius/provider-rabbitmqtf/apis/namespaced/vhost/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Shovel.
func (mg *Shovel) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Vhost),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VhostRef,
		Selector:     mg.Spec.ForProvider.VhostSelector,
		To: reference.To{
			List:    &v1alpha1.VhostList{},
			Managed: &v1alpha1.Vhost{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Vhost")
	}
	mg.Spec.ForProvider.Vhost = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VhostRef = rsp.ResolvedReference

	return nil
}
