// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/binding/v1alpha1"
	v1alpha1exchange "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/exchange/v1alpha1"
	v1alpha1federationupstream "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/federationupstream/v1alpha1"
	v1alpha1operatorpolicy "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/operatorpolicy/v1alpha1"
	v1alpha1permissions "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/permissions/v1alpha1"
	v1alpha1policy "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/policy/v1alpha1"
	v1alpha1queue "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/queue/v1alpha1"
	v1alpha1shovel "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/shovel/v1alpha1"
	v1alpha1topicpermissions "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/topicpermissions/v1alpha1"
	v1alpha1user "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/user/v1alpha1"
	v1alpha1cluster "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/v1alpha1"
	v1beta1 "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/v1beta1"
	v1alpha1vhost "github.com/Volevanius/provider-rabbitmqtf/apis/cluster/vhost/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1exchange.SchemeBuilder.AddToScheme,
		v1alpha1federationupstream.SchemeBuilder.AddToScheme,
		v1alpha1operatorpolicy.SchemeBuilder.AddToScheme,
		v1alpha1permissions.SchemeBuilder.AddToScheme,
		v1alpha1policy.SchemeBuilder.AddToScheme,
		v1alpha1queue.SchemeBuilder.AddToScheme,
		v1alpha1shovel.SchemeBuilder.AddToScheme,
		v1alpha1topicpermissions.SchemeBuilder.AddToScheme,
		v1alpha1user.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1vhost.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
