apiVersion: exchange.rabbitmqtf.crossplane.io/v1alpha1
kind: Exchange
metadata:
  annotations:
    meta.upbound.io/example-id: exchange/v1alpha1/exchange
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    settings:
    - autoDelete: true
      durable: false
      type: fanout
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: guest

---

apiVersion: permissions.rabbitmqtf.crossplane.io/v1alpha1
kind: Permissions
metadata:
  annotations:
    meta.upbound.io/example-id: exchange/v1alpha1/exchange
  labels:
    testing.upbound.io/example-name: guest
  name: guest
spec:
  forProvider:
    permissions:
    - configure: .*
      read: .*
      write: .*
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: vhost.rabbitmqtf.crossplane.io/v1alpha1
kind: Vhost
metadata:
  annotations:
    meta.upbound.io/example-id: exchange/v1alpha1/exchange
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider: {}
